//! Arithmetic in the Galois field GF(2^8).
//!
//! The field is generated by the primitive polynomial
//! `x^8 + x^4 + x^3 + x^2 + 1` (`0x11D`), with `2` as the primitive element.
//! This is the same field used by QR codes, which makes hand-checking against
//! published test vectors straightforward.
//!
//! Addition and subtraction in GF(2^8) are both XOR. Multiplication is done
//! through precomputed log/antilog tables, so every operation below is a
//! constant-time-ish table lookup with no data-dependent branching on the
//! operand values (apart from the zero checks that the field itself requires).

/// The primitive polynomial used to generate the field.
pub const PRIMITIVE_POLY: u16 = 0x11D;

/// The primitive element (generator) of the multiplicative group.
pub const GENERATOR: u8 = 2;

/// Number of elements in the multiplicative group: `2^8 - 1`.
pub const ORDER: usize = 255;

struct Tables {
    exp: [u8; 512],
    log: [u8; 256],
}

// A `static` (not a `const`) so the tables are materialised once in read-only
// memory at compile time; a `const` is substituted at every use site, which
// would re-create 768 bytes of tables on each field operation in debug builds.
static TABLES: Tables = build_tables();

const fn build_tables() -> Tables {
    let mut exp = [0u8; 512];
    let mut log = [0u8; 256];

    let mut x: u16 = 1;
    let mut i = 0usize;
    while i < ORDER {
        exp[i] = x as u8;
        log[x as usize] = i as u8;
        x <<= 1;
        if x & 0x100 != 0 {
            x ^= PRIMITIVE_POLY;
        }
        i += 1;
    }

    // Duplicate the table so that `exp[a + b]` never needs a modular reduction
    // for `a, b < 255`.
    let mut j = 0usize;
    while j < ORDER {
        exp[ORDER + j] = exp[j];
        j += 1;
    }
    // `exp[510]` and `exp[511]` are only reachable through deliberate
    // out-of-range indexing, which the helpers below never perform.
    Tables { exp, log }
}

/// Field addition. In characteristic 2 this is XOR.
#[inline]
#[must_use]
pub const fn add(a: u8, b: u8) -> u8 {
    a ^ b
}

/// Field subtraction. Identical to [`add`] in characteristic 2.
#[inline]
#[must_use]
pub const fn sub(a: u8, b: u8) -> u8 {
    a ^ b
}

/// Field multiplication.
#[inline]
#[must_use]
pub fn mul(a: u8, b: u8) -> u8 {
    if a == 0 || b == 0 {
        return 0;
    }
    let la = TABLES.log[a as usize] as usize;
    let lb = TABLES.log[b as usize] as usize;
    TABLES.exp[la + lb]
}

/// Field division. Returns `0` when `a` is `0`.
///
/// # Panics
/// Panics if `b` is zero, which is division by zero in the field.
#[inline]
#[must_use]
pub fn div(a: u8, b: u8) -> u8 {
    assert!(b != 0, "pz-fec: division by zero in GF(2^8)");
    if a == 0 {
        return 0;
    }
    let la = TABLES.log[a as usize] as usize;
    let lb = TABLES.log[b as usize] as usize;
    TABLES.exp[(la + ORDER - lb) % ORDER]
}

/// Multiplicative inverse.
///
/// # Panics
/// Panics if `a` is zero, which has no inverse.
#[inline]
#[must_use]
pub fn inv(a: u8) -> u8 {
    assert!(a != 0, "pz-fec: zero has no multiplicative inverse");
    TABLES.exp[ORDER - TABLES.log[a as usize] as usize]
}

/// Raise `a` to the (possibly negative) power `n`.
#[inline]
#[must_use]
pub fn pow(a: u8, n: i32) -> u8 {
    if a == 0 {
        return if n == 0 { 1 } else { 0 };
    }
    let la = TABLES.log[a as usize] as i64;
    let order = ORDER as i64;
    let mut e = (la * n as i64) % order;
    if e < 0 {
        e += order;
    }
    TABLES.exp[e as usize]
}

/// Discrete logarithm base [`GENERATOR`].
///
/// # Panics
/// Panics if `a` is zero.
#[inline]
#[must_use]
pub fn log(a: u8) -> u8 {
    assert!(a != 0, "pz-fec: log of zero is undefined");
    TABLES.log[a as usize]
}

/// Antilogarithm: `GENERATOR^n` for `0 <= n < 255`.
#[inline]
#[must_use]
pub fn exp(n: usize) -> u8 {
    TABLES.exp[n % ORDER]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_a_permutation() {
        let mut seen = [false; 256];
        for i in 0..ORDER {
            let v = exp(i);
            assert!(v != 0, "exp table must never produce zero");
            assert!(!seen[v as usize], "exp table repeated {v} at {i}");
            seen[v as usize] = true;
        }
        // Every nonzero element must appear exactly once.
        assert!(seen.iter().skip(1).all(|s| *s));
    }

    #[test]
    fn log_and_exp_round_trip() {
        for a in 1u16..256 {
            let a = a as u8;
            assert_eq!(exp(log(a) as usize), a);
        }
    }

    #[test]
    fn multiplication_is_commutative_and_associative() {
        for a in [0u8, 1, 2, 3, 87, 128, 200, 255] {
            for b in [0u8, 1, 5, 17, 99, 128, 254, 255] {
                assert_eq!(mul(a, b), mul(b, a));
                for c in [0u8, 1, 7, 64, 255] {
                    assert_eq!(mul(mul(a, b), c), mul(a, mul(b, c)));
                }
            }
        }
    }

    #[test]
    fn multiplication_distributes_over_addition() {
        for a in 0u16..256 {
            for b in [0u8, 1, 13, 77, 200, 255] {
                for c in [0u8, 2, 44, 199] {
                    let a = a as u8;
                    assert_eq!(mul(a, add(b, c)), add(mul(a, b), mul(a, c)));
                }
            }
        }
    }

    #[test]
    fn division_inverts_multiplication() {
        for a in 0u16..256 {
            for b in 1u16..256 {
                let (a, b) = (a as u8, b as u8);
                assert_eq!(div(mul(a, b), b), a);
            }
        }
    }

    #[test]
    fn inverse_is_correct() {
        for a in 1u16..256 {
            let a = a as u8;
            assert_eq!(mul(a, inv(a)), 1);
        }
    }

    #[test]
    fn pow_matches_repeated_multiplication() {
        for a in [1u8, 2, 3, 100, 255] {
            let mut acc = 1u8;
            for n in 0..20 {
                assert_eq!(pow(a, n), acc, "a={a} n={n}");
                acc = mul(acc, a);
            }
        }
        // Negative exponents wrap through the group order.
        for a in [1u8, 2, 3, 100, 255] {
            assert_eq!(mul(pow(a, -1), a), 1);
            assert_eq!(pow(a, -3), inv(pow(a, 3)));
        }
        assert_eq!(pow(0, 0), 1);
        assert_eq!(pow(0, 5), 0);
    }

    #[test]
    fn known_qr_vectors() {
        // The QR code specification uses the same field; these products are
        // easy to verify by hand from the generator polynomial.
        assert_eq!(mul(2, 128), 0x1D);
        assert_eq!(mul(76, 43), 251);
        assert_eq!(pow(2, 8), 0x1D);
    }
}
